version: "3.8"

services:
  db:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
